name: OushuDB CI

on: [push]

jobs:
  install:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: brew repo
      run: |
        brew tap chiyang10000/homebrew-tap
        cd `brew --repository`/Library/Taps/chiyang10000/homebrew-tap
        git fetch origin refs/heads/${GITHUB_REF##*/}:refs/remotes/origin/${GITHUB_REF##*/}
        git checkout origin/${GITHUB_REF##*/}
        brew search chiyang10000

    - name: install
      run: |
        npm config delete prefix
        brew install oushudb

    - name: check executable
      timeout-minutes: 1
      run: |
        ls -lt /usr/local/opt/oushudb*
        ls -lt /usr/local/Cellar/oushudb*
        ls -lt /usr/local/Cellar/oushudb/
        # have no idea why brew add unwanted .reinstall suffix
        find /usr/local/Cellar/oushudb/ -name '*.reinstall' -type d -maxdepth 1 | sed -E 's|(.*)\.reinstall|\1.reinstall \1|' | xargs ln -snf
        ls -lt /usr/local/Cellar/oushudb/
        ls -lt /usr/local/opt/oushudb/
        sh -c 'source /usr/local/opt/oushudb/greenplum_path.sh && postgres -V'

    - name: initilize macOS
      run: .github/workflows/scripts/init_macos.sh

    - name: initilize HDFS
      run: .github/workflows/scripts/init_hdfs.sh

    - name: initilize OushuDB
      run: .github/workflows/scripts/init_oushudb.sh

    - name: test
      run: .github/workflows/scripts/test_oushudb.sh

