name: PlanChecker CI

on: [push]

jobs:
  install:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: brew repo
      run: |
        brew tap chiyang10000/homebrew-tap
        cd `brew --repository`/Library/Taps/chiyang10000/homebrew-tap
        git fetch origin refs/heads/${GITHUB_REF##*/}:refs/remotes/origin/${GITHUB_REF##*/}
        git checkout origin/${GITHUB_REF##*/}
        brew search chiyang10000

    - name: install
      run: |
        brew install planchecker
        nohup planchecker &
        ps -ef | grep [p]lanchecker || exit 1
