name: PlanChecker CI

on: [push]

jobs:
  install:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: brew repo
      run: |
        brew tap chiyang10000/homebrew-tap
        brew search chiyang10000

    - name: install
      run: |
        brew install planchecker
        nohup planchecker &
        ps -ef | grep [p]lanchecker || exit 1
